spring:
    rabbitmq:
        host: localhost # rabbitmq的连接地址
        port: 5672 # rabbitmq的连接端口号
        virtual-host: /test # rabbitmq的虚拟host
        username: test123 # rabbitmq的用户名
        password: test123 # rabbitmq的密码
